### ISSUE TITLE
can no connect to p2pool node dgb p2pool

### ISSUE THREAD

**Issue by fullymax** [farsider350/p2pool-dgb-scrypt-350#5]
Unhandled Error
Traceback (most recent call last):
  File "/home/ubuntu/p2pool-dgb-scrypt/p2pool/main.py", line 695, in run
    reactor.run()
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/home/ubuntu/p2pool-dgb-scrypt/p2pool/bitcoin/stratum.py", line 38, in _send_work
    x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
  File "/home/ubuntu/p2pool-dgb-scrypt/p2pool/work.py", line 210, in preprocess_request
    raise jsonrpc.Error_for_code(-12345)(u'p2pool is not connected to any peers')
p2pool.util.jsonrpc.NarrowError: -12345 p2pool is not connected to any peers

Unhandled Error
Traceback (most recent call last):
  File "/home/ubuntu/p2pool-dgb-scrypt/p2pool/main.py", line 695, in run
    reactor.run()
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/home/ubuntu/p2pool-dgb-scrypt/p2pool/bitcoin/stratum.py", line 38, in _send_work
    x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
  File "/home/ubuntu/p2pool-dgb-scrypt/p2pool/work.py", line 210, in preprocess_request
    raise jsonrpc.Error_for_code(-12345)(u'p2pool is not connected to any peers

**Comment by fullymax** [comment]
I can see the pool on my second pc  192.168.0.1:5025 in m local net but can not connect miner too

**Comment by fullymax** [comment]
all ports are open

**Comment by fullymax** [comment]
please help thanks

**Comment by fullymax** [comment]
192.168.0.9 is the pc running the pool

**Comment by fullymax** [comment]
ubuntu  20.04 deck top

**Comment by frstrtr** [comment]
Maybe too late, but if You run a private chain, as I see, you need to set persist = false on one of your pool server, to start Your share-chain.

**Comment by fullymax** [comment]
yes I have ubuntu 20.04 LTC and install the DGB p2pool with Doge and DGB  wallets the pool is connecting to the wallets but when try to connect miner from my local network no luckopen the ports on my router point the miner to the local ip-worker port on my ubuntu pc but no gomaybe i need to install the ubuntu server?    On Saturday, April 10, 2021, 04:27:25 PM CDT, Alec ***@***.***> wrote:  
 
 


Maybe too late, but if You run a private chain, as I see, you need to set persist = false on one of your pool server, to start Your share-chain.

**Comment by frstrtr** [comment]
There is no special difference between server vs desktop Ubuntu, in networking terms... Show your miner configuration strings and digibyte.conf.

**Comment by fullymax** [comment]
the miners is L3+ for server I do the ubuntu pc  local network plus the worker port like 198.162.0.12:portpassword is the same on my dgb conf. worker name- no idea but can not connect the minerI can see the server from my window pc but can not connect miner?thanks for you helpGeorge
    On Sunday, April 11, 2021, 12:35:35 AM CDT, Alec ***@***.***> wrote:  
 
 


There is no special difference between server vs desktop Ubuntu, in networking terms... Show your miner configuration strings and digibyte.conf.

**Comment by farsider350** [comment]
Everything should be working again, upgraded to Digibyte version 8.22 today also
